import { describe, expect, it } from "vitest";
import { readRepoFile } from "../../../../helpers/repo-paths";

describe("Home dock fullscreen", () => {
	it("toggles the dock control and uses the chat area as the fullscreen bounds", () => {
		const panelTabsSource: string = readRepoFile("src", "renderer", "src", "widgets", "panel-tabs", "PanelTabs.tsx");
		const dockSource: string = readRepoFile("src", "renderer", "src", "widgets", "dock", "DockPanelTabs.tsx");
		const dockCss: string = readRepoFile("src", "renderer", "src", "widgets", "dock", "DockPanelTabs.module.css");
		const homeSource: string = readRepoFile("src", "renderer", "src", "widgets", "home", "HomePage.tsx");
		const normalizedHomeSource: string = homeSource.replace(/\s+/gu, " ");
		const homeCss: string = readRepoFile("src", "renderer", "src", "widgets", "home", "HomePage.module.css");
		const shelfSource: string = readRepoFile("src", "renderer", "src", "widgets", "home", "FullscreenComposerShelf.tsx");
		const shelfCss: string = readRepoFile("src", "renderer", "src", "widgets", "home", "FullscreenComposerShelf.module.css");
		const composerSource: string = readRepoFile("src", "renderer", "src", "widgets", "composer", "Composer.tsx");
		const composerCss: string = readRepoFile("src", "renderer", "src", "widgets", "composer", "Composer.module.css");
		const filePanelSource: string = readRepoFile("src", "renderer", "src", "widgets", "files", "FilePanel.tsx");
		const browserCss: string = readRepoFile("src", "renderer", "src", "widgets", "browser", "BrowserPanel.module.css");

		expect(panelTabsSource).toContain('name={isFullscreen ? "compress" : "distraction-free"}');
		expect(panelTabsSource).toContain("aria-pressed={isFullscreen}");
		expect(dockSource).toContain("isFullscreen={isFullscreen}");
		expect(dockSource).toContain('t("dock.tabs.enterFullscreen")');
		expect(dockCss).toContain(".fullscreen");
		expect(dockCss).toContain("padding-top: 0;");
		expect(dockCss.indexOf(".fullscreen")).toBeGreaterThan(dockCss.indexOf(".side"));
		expect(homeSource).toContain("type DockFullscreenPlacement");
		expect(homeSource).toContain("visualSessionLayout.fullscreenDock");
		expect(homeSource).toContain("toggleDockFullscreen");
		expect(homeSource).toContain('size: bottomDockFullscreen');
		expect(normalizedHomeSource).toContain('size: sideDockFullscreen ? "100%"');
		expect(normalizedHomeSource).toContain("size={ bottomDockConfig?.panel.size ?? BOTTOM_DOCK_CLOSED_SIZE }");
		expect(normalizedHomeSource).toContain("size={ sideDockConfig?.panel.size ?? SIDE_DOCK_CLOSED_SIZE }");
		expect(homeSource).toContain("FullscreenComposerShelf");
		expect(homeSource).toContain("renderComposer(true)");
		expect(homeSource).toContain("isFullscreenBrowserPanel");
		expect(homeSource).toContain("isDockFullscreen && !isFullscreenBrowserPanel");
		expect(shelfSource).toContain('name="arrow-down"');
		expect(shelfSource).toContain('name="arrow-top"');
		expect(shelfCss).toContain("width: 16px;");
		expect(shelfCss).toContain("height: 8px;");
		expect(shelfCss).toContain("left: 50%;");
		expect(shelfCss).toContain("translate3d(-50%, calc(100% + var(--ds-space-2)), 0)");
		expect(homeSource).toContain("floating={compact}");
		expect(composerSource).toContain("? { minRows: 1, maxRows: 1 }");
		expect(composerSource).toContain("isFloatingComposerCollapsed");
		expect(composerSource).toContain("onFocusCapture={handleFloatingComposerFocus}");
		expect(composerCss).toContain(".composerRootFloatingCollapsed");
		expect(composerCss).toContain("width: 60%;");
		expect(composerCss).toContain(".composerRootFloatingCollapsed .composerToolbar");
		expect(composerCss).toContain(".composerRootCompact .footer");
		expect(filePanelSource).toContain("bottomSafeArea={0}");
		expect(filePanelSource).not.toContain("EDITOR_BOTTOM_SAFE_AREA");
		expect(browserCss).not.toContain("viewportFullscreen");
		expect(normalizedHomeSource).toContain("data-dock-fullscreen={ activeFullscreenDock ?? undefined }");
		expect(homeCss).toContain("data-fullscreen-motion-disabled=\"true\"");
	});
});
