import { describe, expect, it } from "vitest";
import { readRepoFile } from "../helpers/repo-paths";

describe("Flow home surface", (): void => {
	it("keeps Chat and Flow controlled and routes graph edits through the durable operation outbox", (): void => {
		const sidebar = readRepoFile("src", "renderer", "src", "widgets", "home", "workspace", "HomeWorkspaceSidebar.tsx");
		const home = readRepoFile("src", "renderer", "src", "widgets", "home", "HomePage.tsx");
		const surface = readRepoFile("src", "renderer", "src", "widgets", "flow", "HomeFlowSurface.tsx");
		const welcome = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowWelcome.tsx");
		const nodes = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowNodes.tsx");
		const nodeStyles = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowNodes.module.css");
		const surfaceStyles = readRepoFile(
			"src",
			"renderer",
			"src",
			"widgets",
			"flow",
			"HomeFlowSurface.module.css",
		);
		const picker = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowNodePicker.tsx");
		const shortcutSettings = readRepoFile("src", "renderer", "src", "widgets", "settings", "pages", "studio", "KeyboardShortcutsSettingsPage.tsx");
		const controller = readRepoFile("src", "renderer", "src", "features", "home", "flow", "useHomeFlowController.ts");
		const tree = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowTree.tsx");
		const api = readRepoFile("src", "renderer", "src", "platform", "rpc", "flow-api.ts");
		expect(sidebar).toContain("value={primarySurface}");
		expect(sidebar).toContain("onPrimarySurfaceChange");
		expect(home).toContain('mainSurface === "chat" && workspaceForActions !== null');
		expect(home).toContain("sideDockOpen,");
		expect(home).toContain("requestFlowWelcome");
		expect(home).not.toContain("flowController.createNewFlow");
		expect(home).toContain("flowWelcomeRequest === null ? (flowController.snapshot?.flow.flowId ?? null) : null");
		expect(home).toContain("setFlowWelcomeRequest(null);");
		expect(surface).toContain("sideDockOpen: boolean;");
		expect(surface).toContain("showCreateWelcome");
		expect(surface).toContain("onCreateWelcomeClose");
		expect(surface).toContain('data-side-dock-open={sideDockOpen ? "true" : undefined}');
		expect(surfaceStyles).toContain('.header[data-side-dock-open="true"]');
		expect(surface).toContain("onConnect={onConnect}");
		expect(surface).toContain("sourceHandle: edge.sourcePort");
		expect(surface).toContain("targetHandle: edge.targetPort");
		expect(surface).toContain("onConnectEnd={onConnectEnd}");
		expect(surface).toContain("onReconnect={onReconnect}");
		expect(surface).toContain("onReconnectEnd={onReconnectEnd}");
		expect(surface).toContain("edgesReconnectable={!controller.isGraphLocked}");
		expect(surface).toContain('reconnectable: controller.isGraphLocked ? false : "target" as const');
		expect(surface).toContain("reconnectRadius={12}");
		expect(surface).toContain("connectionRadius={FLOW_CONNECTION_RADIUS}");
		expect(surfaceStyles).toContain(".canvasRegion :global(.react-flow__edgeupdater)");
		expect(surfaceStyles).toContain("pointer-events: all");
		expect(surface).toContain("detachedConnectionSourceRef.current");
		expect(surface).toContain("redirectConnectedInputToNativeReconnect");
		expect(surface).toContain('querySelector<SVGCircleElement>');
		expect(surface).toContain('new MouseEvent("mousedown"');
		expect(surface).toContain("flushSync((): void =>");
		expect(surface).toContain(".filter((edge): boolean => overlayEdgeIds.includes(edge.id))");
		expect(surface).toContain("connectionLineComponent={connectionLineComponent}");
		expect(surface).not.toContain("detachedEdgeIdRef");
		expect(surface).toContain("createConnectedNode");
		expect(surface).toContain("onMoveEnd={onMoveEnd}");
		expect(surface).not.toContain("viewportSaveTimerRef");
		expect(surface).toContain("onMoveStart={onMoveStart}");
		expect(surface).not.toContain('setAttribute("data-flow-moving", "true")');
		expect(surface).not.toContain("setIsViewportMoving");
		expect(surface).not.toContain("requestAnimationFrame(sampleFrame)");
		expect(surface).toContain('performance.clearMeasures("daedalus.flow.interaction")');
		expect(surface).not.toContain("MiniMap");
		expect(surface).toContain("menu={approvalModeMenu}");
		expect(surface).toContain("<Dropdown.Button");
		expect(surface).toContain("menu={runEntryMenu}");
		expect(surface).toContain("entryNodeIds: group.nodeIds");
		expect(surface).toContain("forceNodeIds: forceNodeIds ?? snapshot?.nodes.filter");
		expect(surface).toContain('action === "run-input"');
		expect(surface).toContain("reachableOutputNodeIds([nodeId]");
		expect(surface).toContain("groupFlowRunEntries");
		expect(surface).not.toContain("<Modal");
		expect(surface).not.toContain("runSetup");
		expect(surface).toContain('matchesFlowShortcut(event, "flow.deleteSelection")');
		expect(surface).toContain("snapToGrid={snapToGrid}");
		expect(surface).toContain('name={snapToGrid ? "snap-on" : "snap-off"}');
		expect(surface).toContain('type: "flowGradient"');
		expect(surface).toContain("selectionMode={SelectionMode.Partial}");
		expect(surface).toContain("edgeTypes={edgeTypes}");
		expect(surface).toContain("lastPointerPositionRef");
		expect(surface).not.toContain("renderComposer");
		expect(surface).not.toContain("<Empty");
		expect(surface).toContain('mode="create"');
		expect(surface).toContain("controller.createNewFlow(workspaceId)");
		expect(surface).not.toContain("onStarterSelect={(): void => undefined}");
		expect(welcome).toContain("<Select");
		expect(welcome).toContain("props.onCreate(workspaceId.length === 0 ? null : workspaceId)");
		expect(controller).toContain('kind: "node.create"');
		expect(controller).toContain("flowOperationOutbox.enqueue");
		expect(controller).toContain("kind: \"edge.delete\"");
		expect(controller).toContain("updateNodePosition");
		expect(controller).toContain("ignoreFlowEventsUntilRef");
		expect(controller).toContain("startFlowRun");
		expect(controller).toContain("flowOperationOutbox.flushFully");
		expect(controller).toContain("data.nodeRun");
		expect(controller).toContain("data.run");
		expect(controller).toContain("applyFlowRunFinished");
		expect(controller).toContain("markActiveFlowRead");
		expect(home).toContain("unreadFlowIds: [...flowController.unreadFlowIds]");
		expect(tree).toContain("dot={isUnread}");
		expect(tree).toContain('color="var(--ant-color-primary)"');
		expect(tree).not.toContain("dot={isUnread || runtimeStatus !== undefined}");
		expect(nodes).toContain("resolveFlowCanvasPorts");
		expect(nodes).toContain('schema["x-daedalus-control"]');
		expect(nodes).toContain('control === "provider"');
		expect(nodes).toContain('control === "model"');
		expect(nodes).toContain('control === "reasoning-effort"');
		expect(nodes).toContain('control === "workspace-file"');
		expect(nodes).toContain('name="folder-open"');
		expect(surface).toContain("commitActiveEditor");
		expect(surface).toContain("listProviderModels");
		expect(nodes).toContain("id={parameter.id}");
		expect(nodes).toContain("id={output.id}");
		expect(nodes).toContain("connectedInputIds.has(parameter.id)");
		expect(nodes).toContain("parameter.hideControlWhenConnected");
		expect(nodes).toContain("useUpdateNodeInternals");
		expect(nodes).not.toMatch(/<Collapse(?:\s|>)/);
		expect(nodes).not.toContain("data.onDelete");
		expect(nodes).not.toContain("draftTitle");
		expect(nodes).not.toContain("<footer");
		expect(nodes).not.toContain("<Tag");
		expect(nodes).not.toContain("normalizeFlowNodeRunStatus");
		expect(nodes).toContain('flowNode.typeId === "builtin/flow-input"');
		expect(nodes).toContain('name="play"');
		expect(nodes).toContain('flowNode.typeId === "builtin/output"');
		expect(nodes).toMatch(/className=\{.*styles\.outputResult.*nodrag nowheel/);
		expect(nodes).toContain("<MarkdownContent cacheParsing>{outputMarkdown}</MarkdownContent>");
		expect(nodes).toContain('format === "json"');
		expect(nodes).not.toContain("resultPreview");
		expect(nodeStyles).toContain(".nodeCardSelected");
		expect(nodeStyles).toContain("display: flex;");
		expect(nodeStyles).toContain("flex: 1 1 0;");
		expect(nodeStyles).toContain("text-overflow: ellipsis;");
		expect(nodeStyles).not.toContain("grid-template-columns: 12px");
		expect(nodeStyles).toContain("left: calc(0px - var(--ds-space-3) - 1px);");
		expect(nodeStyles).toContain("transform: translate(-50%, -50%) !important;");
		expect(nodeStyles).not.toContain(".nodeCard:hover");
		expect(nodeStyles).not.toMatch(/\.nodeCard\s*\{[^}]*transition:/u);
		expect(nodeStyles).not.toContain("overflow-clip-margin");
		expect(surfaceStyles).toContain("will-change: transform;");
		expect(surfaceStyles).toContain("backface-visibility: hidden;");
		expect(surfaceStyles).toContain(".canvasRegion :global(.react-flow__viewport)");
		expect(surfaceStyles).not.toContain('[data-flow-resampling="true"]');
		expect(surfaceStyles).not.toContain('[data-flow-moving="true"]');
		expect(surfaceStyles).not.toContain("box-shadow: none;");
		expect(picker).toContain("<Dropdown");
		expect(picker).toContain("popupRender=");
		expect(picker).toContain("children: categoryDefinitions.map");
		expect(picker).toContain('destroyOnHidden={false}');
		expect(picker).toContain("trigger={[]}");
		expect(picker).toContain('document.addEventListener("pointerdown", closeOnOutsidePointerDown, true);');
		expect(picker).toContain('element?.closest("[data-flow-node-picker-popup]")');
		expect(picker).toContain("open ? openCategoryKeys : []");
		expect(picker).toContain("setOpenCategoryKeys([]);");
		expect(picker).toContain("motion: submenuMotion");
		expect(picker).toContain("motionLeave: false");
		expect(picker).toContain("onTitleMouseEnter:");
		expect(picker).not.toContain("flow.editor.picker.hint");
		expect(nodes).not.toContain("portSpacer");
		expect(nodes).not.toContain("selected && definition !== null");
		expect(surface).toContain("clientX + FLOW_NODE_CREATE_OFFSET");
		expect(shortcutSettings).toContain("SHORTCUT_DEFINITIONS");
		expect(shortcutSettings).not.toContain("FlowShortcutReference");
		expect(controller).toContain("next = applyFlowOperation(next, operation");
		expect(controller).toContain("flowOperationOutbox.enqueue");
		expect(controller).toContain("if (repairedConfigByNodeId.size > 0) setSnapshot(next);");
		expect(controller).toContain("const reconnectEdge = useCallback");
		expect(controller).toContain("applyOperations([");
		expect(api).toContain('"flow.patch.commit"');
		expect(api).toContain('"flow.run.start"');
		expect(api).not.toContain('"flow.node.create"');
		expect(api).not.toContain('"flow.node.createConnected"');
	});

	it("keeps plugin node editors on the local sandbox protocol", (): void => {
		const nodes = readRepoFile("src", "renderer", "src", "widgets", "flow", "FlowNodes.tsx");
		const protocol = readRepoFile("src", "main", "services", "plugin-ui-protocol.ts");
		expect(nodes).toContain('sandbox="allow-scripts"');
		expect(nodes).not.toMatch(/sandbox=["'][^"']*allow-same-origin/u);
		expect(nodes).toContain("event.source !== iframeRef.current?.contentWindow");
		expect(nodes).toContain('event.origin !== "null"');
		expect(protocol).toContain('connect-src \'none\'');
		expect(protocol).toContain('plugin.trust !== "trusted"');
		expect(protocol).toContain("MAX_PLUGIN_UI_RESOURCE_BYTES");
		expect(protocol).toContain("realpath");
	});
});
